name: new_fundamental_submission
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  flutter_timezone: ^5.0.1
  google_fonts: ^6.3.2
  http: ^1.5.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.26.2
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
